# docker-compose.yml
version: "3.8"
services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - fiveminutesmarket.env
    depends_on:
      - db
  db:
    image: mysql:5.7.34
    ports:
      - "3306:3306"
    env_file:
      - mysql.env