spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  redis:
    host: ${redis.host}
    port: 6379
  jackson:
    serialization:
      write_dates_as_timestamps: false

kakao:
  admin:
    token: ${kakao.admin.token}
  redirect_domain: http://localhost