spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/fiveminutesmarket?autoreconnect=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: springtest